//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Lines = new HashSet<Line>();
        }
    
        public string P_CODE { get; set; }
        public string P_DESCRIPT { get; set; }
        public Nullable<System.DateTime> P_INDATE { get; set; }
        public Nullable<int> P_QOH { get; set; }
        public Nullable<int> P_MIN { get; set; }
        public Nullable<float> P_PRICE { get; set; }
        public Nullable<float> P_DISCOUNT { get; set; }
        public Nullable<int> V_CODE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Line> Lines { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
